PREFIX bst: <https://aimet-lab.github.io/BISTIRIS#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?category ?type (COUNT(?garment) AS ?garmentCount)
WHERE {
  ?garment a bst:M-Headwear ;
       a ?type ;
       schema:fromLocation ?place .
  ?place a dbo:Place ;
       dbo:elevation ?elevation .

  BIND(xsd:decimal(?elevation) AS ?elevationDecimal)
  BIND(
    IF(?elevation > 600,
       "Elevation > 600 m",
       "Elevation <= 600 m"
    ) AS ?category
  )

  FILTER(?type != owl:NamedIndividual)
  FILTER NOT EXISTS { 
    ?otherType rdfs:subClassOf ?type .
  }
}

GROUP BY ?category ?type
ORDER BY ?category DESC(?garmentCount)
