PREFIX a-lite: <https://w3id.org/arco/ontology/arco-lite/>
PREFIX bst: <https://aimet-lab.github.io/BISTIRIS#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?garmentType ?colour (COUNT(DISTINCT ?place) AS ?frequency)
       (GROUP_CONCAT(DISTINCT STRAFTER(STR(?place), "http://dbpedia.org/resource/"); separator=", ") AS ?places) 
        ?characteristic
WHERE {
    ?garment1 a bst:F-Garment ;
              schema:fromLocation dbr:Galtellì ;
              a ?garmentType ;
              a-lite:hasColour ?colour .
              
    ?characteristic rdfs:subPropertyOf bst:technical_details .
    ?garment1 ?characteristic ?value .

    ?place dbo:neighboringMunicipality dbr:Galtellì ;
           a dbo:Place .

    ?garment2 a bst:F-Garment ;
              schema:fromLocation ?place ;
              a ?garmentType ;
              a-lite:hasColour ?colour ;
              ?characteristic ?value .

    FILTER ( ?garmentType != owl:NamedIndividual )
    FILTER NOT EXISTS { ?OtherClass rdfs:subClassOf ?garmentType }
}
GROUP BY ?garmentType ?colour ?characteristic
ORDER BY DESC(?frequency)
