PREFIX schema: <https://schema.org/>
PREFIX bst: <https://aimet-lab.github.io/BISTIRIS#>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?garment ?place
WHERE {
  
    ?garment a bst:F-Bodice ;
        bst:covers ?otherGarment .
    
    ?otherGarment a bst:F-Jacket ;
      schema:fromLocation ?place .

    FILTER(STRSTARTS(STR(?place), STR(dbr:)))
  
  }
