PREFIX bst: <https://aimet-lab.github.io/BISTIRIS#>
PREFIX schema: <https://schema.org/>

SELECT ?CurlyApronCount ?Frequency
WHERE {
  {
    SELECT (COUNT(DISTINCT ?garment) AS ?CurlyApronCount)
    WHERE {
      ?garment a bst:Curly_apron ;
               bst:coversWithTransparency ?otherGarment .
    }
  }
  {
    SELECT (COUNT(DISTINCT ?CurlyAprons) AS ?total)
    WHERE {
      ?CurlyAprons a bst:Curly_apron .
    }
  }

  BIND( (?CurlyApronCount / ?total) AS ?Frequency )
}
